name: Hello World
author: Valentin Garcia Iriart
description: "Greet someone and record the time"
inputs:
  who_to_greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: The time of the greeting
runs:
  using: "node16"
  main: index.js
  pre: "setup.js" #no anda en private actions
  pre-if: runner.os == 'linux' #condiciones para el pre y el post, solo corre si el S.O es Linux, si no, no lo corre
  post: "cleanup.js"
  post-if: runner.os == 'linux'