name: Checkout
on: [push]

jobs: #lo que hace es descargar los archivos de mi repo y los tira en el directorio en donde estoy laburando, si bien hace ese trabajo
# esta todo hardcodeado y tiene "mucho" código cuando se puede hacer de una manera más sencilla
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout 
              run: |
                  git init
                  git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                  git fetch origin
                  git checkout main  
            - name: List Files After
              run: ls -a      