name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      # credentials:
      #   username:
      #   password:  Las credenciales van unicamente si la imagen de docker es privada
      env:
        API_URL: some-url.com
      ports:
        - 80 # para exponer en el contenedor de docker
      # volumes:
      #   - vol_name:/path/in/container named volumes
      #   - /path/to/container volumenes anonimos
      #   - /path/in/host:/path/in/container bind mount
      # options: --cpus 1 
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17 #corre en un contenedor distinto a los otros 2 trabajos pero compartiendo la misma red
        with:
          entrypoint: /usr/local/bin/node #sobreescribe el entrypoint de la imagen si existe, si no, lo agrega. Esto es en ubuntu y MAC
          #no es siempre necesario el entrypoint como entre la 36 y 37
          args: -p 2+3
      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v