name: External Events
on: 
    repository_dispatch: #it has to be pushed on the default branch (main in this case)
        types: [build]
    

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{github.event.client_payload.env}}
