name: External Events
on: 
    repository_dispatch: #it has to be pushed on the default branch (main in this case)

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Repository Dispatch"
