name: Matrix
on: [push]

jobs:
    node-matrix: #esto es para correr multiples trabajos pero con distintas variables
     strategy:
        matrix:
            os: [ubuntu-latest,windows-latest] #agregando una segunda (bidimensional)
            node-version: [14,15,16] #esta es la matriz (unidimensional)
     runs-on: ${{matrix.os}}
     steps:
        - run: node -v
        - uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}} #asi es como se accede a la matriz, con contextos
        - run: node -v
