name: Reusable Workflow
on:
    workflow_call:
        outputs: 
            date:
                description: "Date Value"
                value: ${{jobs.generate-output.outputs.date}}


jobs:
    nested-workflow-call:
        uses: ValentinDevOps/workflows/.github/workflows/reusable.yaml@main #tenes que poner el path si esta en un repo distinto como aca
        with:
            name: "Valentin"
        secrets:
            access-token: ${{secrets.ACCESS_TOKEN}}
    generate-output:
        runs-on: ubuntu-latest
        outputs:
            date: ${{steps.date-step.outputs.date}}
        steps:
            - run: echo "date=$(date)" >> $GITHUB_OUTPUT
              id: date-step