name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1 #ahora estando en el scope del job, si tooodos los steps tardan mas de un minuto, el workflow se cancela
    steps:
      - name: Step 1
        run: sleep 65
        #timeout-minutes: 1 #si el step no se ejecuta dentro de un minuto falla
      - name: Step 2
        id: step-2
        continue-on-error: true #con esto, si falla, sigue corriendo el resto de los steps
        run: exit 1
      - name: Runs on step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure' 
        run: echo 'Step 2 has failed'
      - name: Runs on Failure
        if: failure()
        run: echo 'Failures'
      - name: Runs on Success
        # This is not needed (DEFAULT BEHAVIOUR)
        if: success()
        run: echo 'Runs on Success'
      - name: Always Runs
        # if: success() || failure()
        if: always()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'