name: Calling Reusable Workflows
on:
    workflow_dispatch:
        inputs:
            name:
                description: "Input description"
                type: string
                default: "Valentin"
                required: false

jobs: #TODO EL TRABAJO USARA EL WORKFLOW, NO VA AL STEP LEVEL PARA REUSAR
    calling-a-reusable-wf: 
        uses: ValentinDevOps/workflows/.github/workflows/reusable.yaml@main #tenes que poner el path si esta en un repo distinto como aca
        with:
            name: ${{inputs.name}}
        secrets:
            access-token: ${{secrets.ACCESS_TOKEN}}
            #si pones inherit en la linea anterior, el reusable puede acceder a todos los secretos de este workflow
    calling-a-reusable-wf-in-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
        secrets:
            access-token: inherit
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-same-repo
        steps:
            - run: echo ${{needs.calling-a-reusable-wf-in-same-repo.outputs.date}}